name: Build & Test library

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        zig-version: [latest, master]
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}

    - name: Check formatting
      run: zig fmt --ast-check --check .

    - name: Build
      run: zig build --summary all
